name: BOOK

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    name: Test and deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - name: Install Julia dependencies
        uses: julia-actions/julia-buildpkg@latest

      - name: Build the book
        run: |
          julia --project -e 'using Books; mkpath("_build"); html()'
        env:
          GKS_ENCODING: "utf8"
          GKSwstype: "100"

      - name: Deploy to secondary branch
        # Always updates documentation when ubuntu passes, which is fine.
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_build/
